name: build avx2

on:
  push:
    branches: 
      - master
      - workflow-windows-releases
  pull_request:
    branches:
      - master
      - workflow-windows-releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: sudo apt update && sudo apt install mingw-w64

      - name: make modern
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-avx2 EXE=stockfish_x64_modern.exe && strip stockfish_x64_modern.exe

      - uses: actions/upload-artifact@v2
        with:
          name: stockfish
          path: src/stockfish*.exe
