name: Stockfish
on:
  push:
    tags:
      - 'sf_*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Stockfish ${{ github.ref_name }}'
          releaseBody: ${{ github.event.head_commit.message }}
          releaseDraft: true
          prerelease: false