name: Stockfish
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Matrix:
    name: Prepare matrices
    runs-on: ubuntu-latest
    outputs:
      arm_matrix: ${{ steps.set-arm-matrix.outputs.arm_matrix }}
      universal_matrix: ${{ steps.set-universal-matrix.outputs.universal_matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: set-universal-matrix
        run: |
          UNIVERSAL_MATRIX=$(jq -c '.' .github/ci/universal_matrix.json)
          echo "UNIVERSAL_MATRIX=$UNIVERSAL_MATRIX" >> $GITHUB_OUTPUT

  UniversalCompilation:
    name: "Universal builds"
    needs: [Matrix]  # Removed other slow jobs from needs
    uses: ./.github/workflows/universal_compilation.yml
