name: Stockfish
on:
  push:
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Stockfish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      CXXFLAGS: "-Werror"
    strategy:
      matrix:
        config:
          # set the variable for the required tests:
          # run_expensive_tests: true
          # run_32bit_tests: true
          # run_64bit_tests: true
          # run_armv8_tests: true
          # run_armv7_tests: true
          - {
              name: "Ubuntu 20.04 GCC",
              os: ubuntu-20.04,
              compiler: g++,
              comp: gcc,
              run_expensive_tests: false,
              run_32bit_tests: false,
              run_64bit_tests: true,
              shell: 'bash {0}'
            }
          - {
              name: "Ubuntu 20.04 Clang",
              os: ubuntu-20.04,
              compiler: clang++,
              comp: clang,
              run_32bit_tests: false,
              run_64bit_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "Ubuntu 20.04 NDK armv8",
              os: ubuntu-20.04,
              compiler: aarch64-linux-android21-clang++,
              comp: ndk,
              run_armv8_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "Ubuntu 20.04 NDK armv7",
              os: ubuntu-20.04,
              compiler: armv7a-linux-androideabi21-clang++,
              comp: ndk,
              run_armv7_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "MacOS 12 Apple Clang",
              os: macos-12,
              compiler: clang++,
              comp: clang,
              run_64bit_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "MacOS 12 GCC 11",
              os: macos-12,
              compiler: g++-11,
              comp: gcc,
              run_64bit_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "Windows 2022 Mingw-w64 GCC x86_64",
              os: windows-2022,
              compiler: g++,
              comp: mingw,
              run_64bit_tests: true,
              msys_sys: 'mingw64',
              msys_env: 'x86_64-gcc',
              shell: 'msys2 {0}'
            }
          - {
              name: "Windows 2022 Mingw-w64 GCC i686",
              os: windows-2022,
              compiler: g++,
              comp: mingw,
              run_32bit_tests: false,
              msys_sys: 'mingw32',
              msys_env: 'i686-gcc',
              shell: 'msys2 {0}'
            }
          - {
              name: "Windows 2022 Mingw-w64 Clang x86_64",
              os: windows-2022,
              compiler: clang++,
              comp: clang,
              run_64bit_tests: false,
              msys_sys: 'clang64',
              msys_env: 'clang-x86_64-clang',
              shell: 'msys2 {0}'
            }

    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install expect valgrind g++-multilib qemu-user

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.msys_sys}}
          install: mingw-w64-${{matrix.config.msys_env}} make git expect

      - name: Download the used network from the fishtest framework
        run: |
          make net

      - name: Extract the bench number from the commit history
        run: |
          git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
          [ -s git_sig ] && echo "benchref=$(cat git_sig)" >> $GITHUB_ENV && echo "Reference bench:" $(cat git_sig) || echo "No bench found"

      - name: Extract the commit info from the commit history
        run: |
          git show --no-patch --no-notes --pretty='%cs-%h' HEAD > git_commit

      - name: Check compiler
        run: |
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          $COMPILER -v

      - name: Test help target
        run: |
          make help

      # x86-64 tests

      - name: Test x86-64-modern build
        if: ${{ matrix.config.run_64bit_tests }}
        run: |
          make clean
          make -j2 ARCH=x86-64-modern build
          ../tests/signature.sh $benchref
          if [ "$RUNNER_OS" == "Windows" ]; then
            mv stockfish.exe stockfish_$(cat ../git_commit).exe
          else
            mv stockfish stockfish_$(cat ../git_commit)
          fi
          mv stockfish_$(cat ../git_commit) ..
          make clean
          rm nn-*.nnue

      - uses: actions/upload-artifact@v3
        with:
          name: stockfish_x86-64-modern
          path: |
            'AUTHORS'
            'Copying.txt'
            'stockfish_$(cat ../git_commit)*'
