name: Universal Compilation
on:
  workflow_call:
jobs:
  UniversalWindows:
    name: Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup msys and install required packages
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc make git zip

      - name: Download SDE package
        uses: petarpetrovt/setup-sde@31aa4a8e85e109bef00f1d838613fcc6ec421271 # v5.0
        with:
          environmentVariableName: SDE_DIR
          sdeVersion: 9.58.0

      - name: Check Git status before build
        run: |
          echo "=== BEFORE BUILD STATUS ==="
          git status || true
          echo "=== BEFORE BUILD DIFF ==="
          git diff || true
